version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes: 
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - product:/var/lib/mysql

volumes:
  product:
  init.sql: